### ISSUE TITLE
Denial of Service with multipart forms when '=' not found

### ISSUE THREAD

**Issue by silabs-steveegerter** [weston-embedded/uC-HTTP#1]
if the '=' character is not found in a multipart form request,a NULL pointer is returned in Str_Char_N, this pointer is then incremented and dereferenced which can lead to a crash. See HTTPsReq_HdrParse() for details. I recommend adding a test for NULL.

**Comment by wes-jmagasrevy** [comment]
Fixed https://github.com/weston-embedded/uC-HTTP/issues/5
